$ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "udacity-ml-microservice" already exists
NAME                      READY   STATUS    RESTARTS      AGE
udacity-ml-microservice   1/1     Running   2 (11m ago)   36m
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80

$ kubectl logs udacity-ml-microservice
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 417-884-185
[2022-07-05 10:06:36,856] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-07-05 10:06:36,867] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-07-05 10:06:36,875] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-07-05 10:06:36,877] INFO in app: Prediction: [20.35373177134412]
127.0.0.1 - - [05/Jul/2022 10:06:36] "POST /predict HTTP/1.1" 200 -